# Generated by Django 3.2.16 on 2023-09-16 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fcm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=400, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgendaEventoColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(editable=False, verbose_name='Creado')),
                ('modificado', models.DateTimeField(verbose_name='Actualizado')),
                ('color', models.CharField(max_length=7, verbose_name='Color')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Agenda evento color',
                'verbose_name_plural': 'Agenda evento colores',
            },
        ),
        migrations.CreateModel(
            name='AgendaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(editable=False, verbose_name='Creado')),
                ('modificado', models.DateTimeField(verbose_name='Actualizado')),
                ('inicio', models.DateTimeField(db_index=True, verbose_name='Inicio evento')),
                ('fin', models.DateTimeField(db_index=True, verbose_name='Fin evento')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título')),
                ('dia_completo', models.BooleanField(default=True, verbose_name='Todo el día')),
                ('aviso_email', models.BooleanField(default=False, verbose_name='Avisar con email')),
                ('aviso_movil', models.BooleanField(default=False, verbose_name='Avisar con móvil')),
                ('email_enviado', models.DateTimeField(blank=True, null=True, verbose_name='Email enviado')),
                ('movil_enviado', models.DateTimeField(blank=True, null=True, verbose_name='Móvil enviado')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendario.agendaeventocolor', verbose_name='Color')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Agenda evento',
                'verbose_name_plural': 'Agenda eventos',
            },
        ),
    ]
