# Generated by Django 3.2.16 on 2023-09-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_agendaeventopredefinido'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaeventopredefinido',
            name='aviso_email',
            field=models.BooleanField(default=False, verbose_name='Avisar con email'),
        ),
        migrations.AddField(
            model_name='agendaeventopredefinido',
            name='aviso_movil',
            field=models.BooleanField(default=False, verbose_name='Avisar con móvil'),
        ),
    ]
